//@ts-check
/**
 * Generates `src/helpers/is.ts` by scanning `grandma3-types` for every type
 * alias of the form `type X = Obj<'ClassName', ...> & ...` and emitting a
 * runtime `is.<TypeName>` guard that checks `x.GetClass() === 'ClassName'`.
 */

import { createRequire } from 'node:module';
import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import ts from 'typescript';

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(here, '..');
const outPath = resolve(projectRoot, 'src/helpers/is.ts');

const typesPkgDir = dirname(require.resolve('grandma3-types/package.json'));
const typingsDir = join(typesPkgDir, 'typings');

/**
 * @param {string} dir
 * @returns {Generator<string>}
 */
function* walk(dir) {
	for (const entry of readdirSync(dir)) {
		const full = join(dir, entry);
		const stat = statSync(full);
		if (stat.isDirectory()) {
			yield* walk(full);
		} else if (stat.isFile() && full.endsWith('.d.ts')) {
			yield full;
		}
	}
}

/**
 * Returns the string-literal class name if `type` is (or intersects with) an
 * `Obj<'ClassName', ...>` reference. Otherwise returns null.
 *
 * @param {ts.TypeNode} type
 * @returns {string | null}
 */
function extractObjClassLiteral(type) {
	const members = ts.isIntersectionTypeNode(type) ? Array.from(type.types) : [type];
	for (const member of members) {
		if (!ts.isTypeReferenceNode(member)) continue;
		if (!ts.isIdentifier(member.typeName) || member.typeName.text !== 'Obj') continue;
		const first = member.typeArguments?.[0];
		if (
			first &&
			ts.isLiteralTypeNode(first) &&
			ts.isStringLiteral(first.literal)
		) {
			return first.literal.text;
		}
	}
	return null;
}

/** @type {Map<string, string>} */
const guards = new Map();

for (const file of walk(typingsDir)) {
	const text = readFileSync(file, 'utf8');
	const sourceFile = ts.createSourceFile(file, text, ts.ScriptTarget.Latest, false);
	ts.forEachChild(sourceFile, (node) => {
		if (!ts.isTypeAliasDeclaration(node)) return;
		const classLiteral = extractObjClassLiteral(node.type);
		if (classLiteral === null) return;
		const typeName = node.name.text;
		const existing = guards.get(typeName);
		if (existing && existing !== classLiteral) {
			console.warn(
				`[generate-is] conflicting class literal for ${typeName}: ` +
					`'${existing}' vs '${classLiteral}' — keeping first`,
			);
			return;
		}
		guards.set(typeName, classLiteral);
	});
}

const sorted = Array.from(guards.entries()).sort(([a], [b]) => a.localeCompare(b));

const lines = [
	'// AUTO-GENERATED by scripts/generate-is.mjs — do not edit.',
	'',
	'function isClass<T extends GenericObj>(className: string) {',
	'\treturn (x: GenericObj): x is T => x.GetClass() === className;',
	'}',
	'',
	'export const is = {',
	...sorted.map(
		([typeName, classLiteral]) =>
			`\t${typeName}: isClass<${typeName}>('${classLiteral}'),`,
	),
	'};',
	'',
];

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join('\n'));

console.log(
	`[generate-is] wrote ${guards.size} guard${guards.size === 1 ? '' : 's'} to ${relative(
		projectRoot,
		outPath,
	)}`,
);
